In [ ]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

In [ ]:
sentence = 'I like you'
token = nltk.word_tokenize(sentence)
token

['I', 'like', 'you']

In [ ]:
nltk.pos_tag(token)


[('I', 'PRP'), ('like', 'VBP'), ('you', 'PRP')]

In [ ]:
sentence = 'I am like you'
token = nltk.word_tokenize(sentence)
nltk.pos_tag(token)

[('I', 'PRP'), ('am', 'VBP'), ('like', 'IN'), ('you', 'PRP')]

In [ ]:
!pip install pythainlp[full]

In [ ]:
import pythainlp

In [ ]:
from pythainlp import sent_tokenize, word_tokenize

In [ ]:
text = 'หัวหน้าฮงเป็นตัวอย่างของคนที่ดีเกินไปจนทำร้ายตัวเอง'

In [ ]:
sent = word_tokenize(text, engine='newmm')
print(sent)

['หัวหน้า', 'ฮง', 'เป็น', 'ตัวอย่าง', 'ของ', 'คน', 'ที่', 'ดี', 'เกินไป', 'จน', 'ทำร้าย', 'ตัวเอง']


In [ ]:
from pythainlp import Tokenizer
from pythainlp.util import Trie
from pythainlp.corpus.common import thai_words
words = ["ดีเกินไป"]
custom_words_list = set(thai_words())
custom_words_list.update(words)
trie = Trie(words=custom_words_list)
custom_tokenizer = Tokenizer(custom_dict=trie, engine='newmm')
sent = custom_tokenizer.word_tokenize(text)
print(sent)

['หัวหน้า', 'ฮง', 'เป็น', 'ตัวอย่าง', 'ของ', 'คน', 'ที่', 'ดีเกินไป', 'จน', 'ทำร้าย', 'ตัวเอง']


In [ ]:
from pythainlp.tag import pos_tag, pos_tag_sents

In [ ]:
pos_tag(sent) # Default engine="perceptron" # (default) corpus="orchid"

[('หัวหน้า', 'NCMN'),
 ('ฮง', 'NCMN'),
 ('เป็น', 'VSTA'),
 ('ตัวอย่าง', 'NCMN'),
 ('ของ', 'RPRE'),
 ('คน', 'NCMN'),
 ('ที่', 'PREL'),
 ('ดีเกินไป', 'VSTA'),
 ('จน', 'JSBR'),
 ('ทำร้าย', 'DONM'),
 ('ตัวเอง', 'PDMN')]

In [ ]:
pos_tag(sent, engine="unigram")

[('หัวหน้า', 'NCMN'),
 ('ฮง', ''),
 ('เป็น', 'VSTA'),
 ('ตัวอย่าง', 'NCMN'),
 ('ของ', 'RPRE'),
 ('คน', 'CNIT'),
 ('ที่', 'PREL'),
 ('ดีเกินไป', ''),
 ('จน', 'JSBR'),
 ('ทำร้าย', ''),
 ('ตัวเอง', 'PDMN')]

In [ ]:
pos_tag(sent, corpus="orchid_ud")

[('หัวหน้า', 'NOUN'),
 ('ฮง', 'NOUN'),
 ('เป็น', 'VERB'),
 ('ตัวอย่าง', 'NOUN'),
 ('ของ', 'ADP'),
 ('คน', 'NOUN'),
 ('ที่', 'SCONJ'),
 ('ดีเกินไป', 'VERB'),
 ('จน', 'SCONJ'),
 ('ทำร้าย', 'ADJ'),
 ('ตัวเอง', 'PRON')]

In [ ]:
pos_tag(sent, corpus="pud") #pud - Parallel Universal Dependencies (PUD)

[('หัวหน้า', 'NOUN'),
 ('ฮง', 'PROPN'),
 ('เป็น', 'AUX'),
 ('ตัวอย่าง', 'NOUN'),
 ('ของ', 'ADP'),
 ('คน', 'NOUN'),
 ('ที่', 'DET'),
 ('ดีเกินไป', 'VERB'),
 ('จน', 'ADP'),
 ('ทำร้าย', 'ADP'),
 ('ตัวเอง', 'PRON')]

In [ ]:
ิิ

In [ ]:
import requests
 
url = "https://api.aiforthai.in.th/tpos"
text = 'หัวหน้าฮงเป็นตัวอย่างของคนที่ดีเกินไปจนทำร้ายตัวเอง'

params = {'text':text}
 
headers = {
    'Apikey': "",
    }
 
response = requests.get(url, headers=headers, params=params)
 
res = response.json()

for word, pos in zip(res['words'], res['tags']):
  print(word, pos)


หัวหน้า NN
ฮง NR
เป็น VV
ตัวอย่าง NN
ของ P
คน NN
ที่ COMP
ดี VA
เกิน ADV
ไป VV
จน CNJ
ทำร้าย VV
ตัว PPER
เอง PPER


Ref https://github.com/AiswaryaSrinivas/DataScienceWithPython

In [ ]:
!pip install sklearn_crfsuite

In [ ]:
import nltk, re, pprint
import numpy as np
import pandas as pd
import requests
import matplotlib.pyplot as plt
import seaborn as sns
import pprint, time
import random
from sklearn.model_selection import train_test_split
from nltk.tokenize import word_tokenize
from sklearn_crfsuite import CRF
from sklearn_crfsuite import metrics
from sklearn_crfsuite import scorers
from collections import Counter

PennTree Bank Corpus, with the universal Tag Set. This tag set h

In [ ]:
import nltk
nltk.download('treebank')
nltk.download('universal_tagset')

In [ ]:
tagged_sentence = nltk.corpus.treebank.tagged_sents(tagset='universal')

In [ ]:
print("Number of Tagged Sentences ",len(tagged_sentence))
tagged_words=[tup for sent in tagged_sentence for tup in sent]
print("Total Number of Tagged words", len(tagged_words))
vocab=set([word for word,tag in tagged_words])
print("Vocabulary of the Corpus",len(vocab))
tags=set([tag for word,tag in tagged_words])
print("Number of Tags in the Corpus ",len(tags))

Number of Tagged Sentences  3914
Total Number of Tagged words 100676
Vocabulary of the Corpus 12408
Number of Tags in the Corpus  12


In [ ]:
train_set, test_set = train_test_split(tagged_sentence,test_size=0.2,random_state=1234)
print("Number of Sentences in Training Data ",len(train_set))
print("Number of Sentences in Testing Data ",len(test_set))

Number of Sentences in Training Data  3131
Number of Sentences in Testing Data  783


Define the feature function. The following features can be used
Is the first letter capitalised.

1.  Is the first letter capitalised.
2.  Is it the first word in the sentence?
3.  Is it the last word?
4.  What is the prefix of the word?
5.  What is the suffix of the word?
6.  Is the complete word captilised?
7.  What is the previous word?
8.  What is the next word?
9.   Is it numeric?
10.  Is it alphanumeric?
11.  Is there an hyphen in the word?



In [ ]:
def features(sentence,index):
    ### sentence is of the form [w1,w2,w3,..], index is the position of the word in the sentence
    return {
        'is_first_capital':int(sentence[index][0].isupper()),
        'is_first_word': int(index==0),
        'is_last_word':int(index==len(sentence)-1),
        'is_complete_capital': int(sentence[index].upper()==sentence[index]),
        'prev_word':'' if index==0 else sentence[index-1],
        'next_word':'' if index==len(sentence)-1 else sentence[index+1],
        'is_numeric':int(sentence[index].isdigit()),
        'is_alphanumeric': int(bool((re.match('^(?=.*[0-9]$)(?=.*[a-zA-Z])',sentence[index])))),
        'prefix_1':sentence[index][0],
        'prefix_2': sentence[index][:2],
        'prefix_3':sentence[index][:3],
        'prefix_4':sentence[index][:4],
        'suffix_1':sentence[index][-1],
        'suffix_2':sentence[index][-2:],
        'suffix_3':sentence[index][-3:],
        'suffix_4':sentence[index][-4:],
        'word_has_hyphen': 1 if '-' in sentence[index] else 0
        
        
    }

Need to seperate labels and the sentences in both training and test data

In [ ]:
def untag(sentence):
    return [word for word,tag in sentence]


def prepareData(tagged_sentences):
    X,y=[],[]
    for sentences in tagged_sentences:
        X.append([features(untag(sentences), index) for index in range(len(sentences))])
        y.append([tag for word,tag in sentences])
    return X,y

In [ ]:
X_train,y_train=prepareData(train_set)
X_test,y_test=prepareData(test_set)

In [ ]:
X_train[0]

[{'is_alphanumeric': 0,
  'is_complete_capital': 0,
  'is_first_capital': 1,
  'is_first_word': 1,
  'is_last_word': 0,
  'is_numeric': 0,
  'next_word': 'Wall',
  'prefix_1': 'O',
  'prefix_2': 'On',
  'prefix_3': 'On',
  'prefix_4': 'On',
  'prev_word': '',
  'suffix_1': 'n',
  'suffix_2': 'On',
  'suffix_3': 'On',
  'suffix_4': 'On',
  'word_has_hyphen': 0},
 {'is_alphanumeric': 0,
  'is_complete_capital': 0,
  'is_first_capital': 1,
  'is_first_word': 0,
  'is_last_word': 0,
  'is_numeric': 0,
  'next_word': 'Street',
  'prefix_1': 'W',
  'prefix_2': 'Wa',
  'prefix_3': 'Wal',
  'prefix_4': 'Wall',
  'prev_word': 'On',
  'suffix_1': 'l',
  'suffix_2': 'll',
  'suffix_3': 'all',
  'suffix_4': 'Wall',
  'word_has_hyphen': 0},
 {'is_alphanumeric': 0,
  'is_complete_capital': 0,
  'is_first_capital': 1,
  'is_first_word': 0,
  'is_last_word': 0,
  'is_numeric': 0,
  'next_word': 'men',
  'prefix_1': 'S',
  'prefix_2': 'St',
  'prefix_3': 'Str',
  'prefix_4': 'Stre',
  'prev_word': 'Wal

In [ ]:
y_train[0]

['ADP',
 'NOUN',
 'NOUN',
 'NOUN',
 'CONJ',
 'NOUN',
 'VERB',
 'ADP',
 'ADJ',
 'NOUN',
 '.',
 'X',
 'VERB',
 'NUM',
 'DET',
 'ADV',
 'ADV',
 'PRON',
 'VERB',
 'ADP',
 'NOUN',
 'X',
 '.']

Let us fit a CRF model with the default Parameters¶

In [ ]:
crf = CRF(
    algorithm='lbfgs',
    c1=0.01,
    c2=0.1,
    max_iterations=100,
    all_possible_transitions=True
)
crf.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CRF(algorithm='lbfgs', all_possible_states=None, all_possible_transitions=True,
    averaging=None, c=None, c1=0.01, c2=0.1, calibration_candidates=None,
    calibration_eta=None, calibration_max_trials=None, calibration_rate=None,
    calibration_samples=None, delta=None, epsilon=None, error_sensitive=None,
    gamma=None, keep_tempfiles=None, linesearch=None, max_iterations=100,
    max_linesearch=None, min_freq=None, model_filename=None, num_memories=None,
    pa_type=None, period=None, trainer_cls=None, variance=None, verbose=False)

In [ ]:
y_pred=crf.predict(X_test)

In [ ]:
metrics.flat_f1_score(y_test, y_pred,average='weighted',labels=crf.classes_)

0.9738471726864286

In [ ]:
y_pred_train=crf.predict(X_train)
metrics.flat_f1_score(y_train, y_pred_train,average='weighted',labels=crf.classes_)

0.9963402924209424

In [ ]:
print(metrics.flat_classification_report(
    y_test, y_pred, labels=crf.classes_, digits=3
))

              precision    recall  f1-score   support

         ADP      0.979     0.985     0.982      1869
        NOUN      0.966     0.977     0.972      5606
        CONJ      0.994     0.994     0.994       480
        VERB      0.964     0.960     0.962      2722
         ADJ      0.911     0.874     0.892      1274
           .      1.000     1.000     1.000      2354
           X      1.000     0.997     0.998      1278
         NUM      0.991     0.993     0.992       671
         DET      0.994     0.995     0.994      1695
         ADV      0.927     0.909     0.918       585
        PRON      0.998     0.998     0.998       562
         PRT      0.979     0.982     0.980       614

    accuracy                          0.974     19710
   macro avg      0.975     0.972     0.974     19710
weighted avg      0.974     0.974     0.974     19710



Ref https://nlpforhackers.io/lstm-pos-tagger-keras/

In [ ]:
import nltk
nltk.download('treebank')
tagged_sentences = nltk.corpus.treebank.tagged_sents()
 
print(tagged_sentences[0])
print("Tagged sentences: ", len(tagged_sentences))
print("Tagged words:", len(nltk.corpus.treebank.tagged_words()))

[nltk_data] Downloading package treebank to /root/nltk_data...
[nltk_data]   Unzipping corpora/treebank.zip.
[('Pierre', 'NNP'), ('Vinken', 'NNP'), (',', ','), ('61', 'CD'), ('years', 'NNS'), ('old', 'JJ'), (',', ','), ('will', 'MD'), ('join', 'VB'), ('the', 'DT'), ('board', 'NN'), ('as', 'IN'), ('a', 'DT'), ('nonexecutive', 'JJ'), ('director', 'NN'), ('Nov.', 'NNP'), ('29', 'CD'), ('.', '.')]
Tagged sentences:  3914
Tagged words: 100676


In [ ]:
import numpy as np
 
sentences, sentence_tags =[], [] 
for tagged_sentence in tagged_sentences:
    sentence, tags = zip(*tagged_sentence)
    sentences.append(np.array(sentence))
    sentence_tags.append(np.array(tags))
 
# Let's see how a sequence looks
 
print(sentences[5])
print(sentence_tags[5])

['Lorillard' 'Inc.' ',' 'the' 'unit' 'of' 'New' 'York-based' 'Loews'
 'Corp.' 'that' '*T*-2' 'makes' 'Kent' 'cigarettes' ',' 'stopped' 'using'
 'crocidolite' 'in' 'its' 'Micronite' 'cigarette' 'filters' 'in' '1956'
 '.']
['NNP' 'NNP' ',' 'DT' 'NN' 'IN' 'JJ' 'JJ' 'NNP' 'NNP' 'WDT' '-NONE-' 'VBZ'
 'NNP' 'NNS' ',' 'VBD' 'VBG' 'NN' 'IN' 'PRP$' 'NN' 'NN' 'NNS' 'IN' 'CD'
 '.']


In [ ]:
from sklearn.model_selection import train_test_split
 
 
(train_sentences, 
 test_sentences, 
 train_tags, 
 test_tags) = train_test_split(sentences, sentence_tags, test_size=0.2)

**Keras also needs to work with numbers,**

In [ ]:
words, tags = set([]), set([])
 
for s in train_sentences:
    for w in s:
        words.add(w.lower())
 
for ts in train_tags:
    for t in ts:
        tags.add(t)
 
word2index = {w: i + 2 for i, w in enumerate(list(words))}
word2index['-PAD-'] = 0  # The special value used for padding
word2index['-OOV-'] = 1  # The special value used for OOVs
 
tag2index = {t: i + 1 for i, t in enumerate(list(tags))}
tag2index['-PAD-'] = 0  # The special value used to padding

Let’s now convert the word dataset to integer dataset, both the words and the tags.

In [ ]:
train_sentences_X, test_sentences_X, train_tags_y, test_tags_y = [], [], [], []
 
for s in train_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w.lower()])
        except KeyError:
            s_int.append(word2index['-OOV-'])
 
    train_sentences_X.append(s_int)
 
for s in test_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w.lower()])
        except KeyError:
            s_int.append(word2index['-OOV-'])
 
    test_sentences_X.append(s_int)
 
for s in train_tags:
    train_tags_y.append([tag2index[t] for t in s])
 
for s in test_tags:
    test_tags_y.append([tag2index[t] for t in s])
 
print(train_sentences_X[0])
print(test_sentences_X[0])
print(train_tags_y[0])
print(test_tags_y[0])

[7679, 767, 7174, 3919, 575, 5272, 7679, 1743, 3408, 7174, 1225, 575, 3401, 9923, 787, 1225, 787, 9483, 4521, 5137]
[9267, 1534, 255, 9058, 9923, 8879, 3104, 1025, 1622, 3994, 5404, 3104, 425, 4521, 5137]
[29, 38, 42, 44, 38, 33, 29, 12, 12, 42, 19, 2, 22, 39, 22, 19, 22, 33, 41, 20]
[41, 39, 21, 41, 39, 21, 26, 1, 40, 12, 21, 26, 1, 41, 20]


In [ ]:
MAX_LENGTH = len(max(train_sentences_X, key=len))
print(MAX_LENGTH)  # 271

128


In [ ]:
from keras.preprocessing.sequence import pad_sequences
 
train_sentences_X = pad_sequences(train_sentences_X, maxlen=MAX_LENGTH, padding='post')
test_sentences_X = pad_sequences(test_sentences_X, maxlen=MAX_LENGTH, padding='post')
train_tags_y = pad_sequences(train_tags_y, maxlen=MAX_LENGTH, padding='post')
test_tags_y = pad_sequences(test_tags_y, maxlen=MAX_LENGTH, padding='post')
 
print(train_sentences_X[0])
print(test_sentences_X[0])
print(train_tags_y[0])
print(test_tags_y[0])

[7679  767 7174 3919  575 5272 7679 1743 3408 7174 1225  575 3401 9923
  787 1225  787 9483 4521 5137    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0]
[9267 1534  255 9058 9923 8879 3104 1025 1622 3994 5404 3104  425 4521
 5137    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, InputLayer, Bidirectional, TimeDistributed, Embedding, Activation
from keras.optimizers import adam_v2
 
 
model = Sequential()
model.add(InputLayer(input_shape=(MAX_LENGTH, )))
model.add(Embedding(len(word2index), 128))
model.add(Bidirectional(LSTM(256, return_sequences=True)))
model.add(TimeDistributed(Dense(len(tag2index))))
model.add(Activation('softmax'))
 
model.compile(loss='categorical_crossentropy',
              optimizer=adam_v2.Adam(0.001),
              metrics=['accuracy'])
 
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 128, 128)          1289856   
_________________________________________________________________
bidirectional (Bidirectional (None, 128, 512)          788480    
_________________________________________________________________
time_distributed (TimeDistri (None, 128, 47)           24111     
_________________________________________________________________
activation (Activation)      (None, 128, 47)           0         
Total params: 2,102,447
Trainable params: 2,102,447
Non-trainable params: 0
_________________________________________________________________


**One-Hot Encoded tags.**

In [ ]:
def to_categorical(sequences, categories):
    cat_sequences = []
    for s in sequences:
        cats = []
        for item in s:
            cats.append(np.zeros(categories))
            cats[-1][item] = 1.0
        cat_sequences.append(cats)
    return np.array(cat_sequences)

In [ ]:
cat_train_tags_y = to_categorical(train_tags_y, len(tag2index))
print(cat_train_tags_y[0])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [ ]:
model.fit(train_sentences_X, to_categorical(train_tags_y, len(tag2index)), batch_size=128, epochs=40, validation_split=0.2)


Epoch 1/40
20/20 [==============================] - 12s 174ms/step - loss: 1.6232 - accuracy: 0.7595 - val_loss: 0.7547 - val_accuracy: 0.8025
Epoch 2/40
20/20 [==============================] - 2s 119ms/step - loss: 0.6986 - accuracy: 0.8046 - val_loss: 0.6683 - val_accuracy: 0.8114
Epoch 3/40
20/20 [==============================] - 2s 119ms/step - loss: 0.6485 - accuracy: 0.8182 - val_loss: 0.6345 - val_accuracy: 0.8271
Epoch 4/40
20/20 [==============================] - 2s 119ms/step - loss: 0.6199 - accuracy: 0.8250 - val_loss: 0.6065 - val_accuracy: 0.8254
Epoch 5/40
20/20 [==============================] - 2s 118ms/step - loss: 0.5972 - accuracy: 0.8265 - val_loss: 0.5901 - val_accuracy: 0.8311
Epoch 6/40
20/20 [==============================] - 2s 117ms/step - loss: 0.5885 - accuracy: 0.8284 - val_loss: 0.5858 - val_accuracy: 0.8412
Epoch 7/40
20/20 [==============================] - 2s 118ms/step - loss: 0.5774 - accuracy: 0.8358 - val_loss: 0.5701 - val_accuracy: 0.8407
Epoch

In [ ]:
scores = model.evaluate(test_sentences_X, to_categorical(test_tags_y, len(tag2index)))
print(f"{model.metrics_names[1]}: {scores[1] * 100}")   # acc: 99.09751977804825
 

25/25 [==============================] - 1s 34ms/step - loss: 0.0745 - accuracy: 0.9814
accuracy: 98.14016819000244


In [ ]:
test_samples = [
    "running is very important for me .".split(),
    "I was running every day for a month .".split()
]
print(test_samples)

[['running', 'is', 'very', 'important', 'for', 'me', '.'], ['I', 'was', 'running', 'every', 'day', 'for', 'a', 'month', '.']]


In [ ]:
test_samples_X = []
for s in test_samples:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w.lower()])
        except KeyError:
            s_int.append(word2index['-OOV-'])
    test_samples_X.append(s_int)
 
test_samples_X = pad_sequences(test_samples_X, maxlen=MAX_LENGTH, padding='post')
print(test_samples_X)

[[3124 3919  464 1941 5272 2997 5137    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [9267 4457 3124 9394 4251 5272 3952 1485 5137    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0

In [ ]:
predictions = model.predict(test_samples_X)
print(predictions, predictions.shape)

[[[2.83112720e-04 5.65613445e-04 1.15833466e-03 ... 9.13295243e-03
   2.27518035e-06 4.32581983e-05]
  [1.09070343e-05 1.20216409e-05 9.25535971e-07 ... 9.92994130e-01
   2.00588275e-07 4.57721262e-06]
  [4.33478817e-05 4.69316932e-04 1.21529889e-03 ... 1.92207191e-03
   1.03022765e-04 3.17449599e-06]
  ...
  [9.99973893e-01 7.66782159e-06 7.65984343e-09 ... 3.24443805e-10
   4.99227826e-06 1.31795090e-07]
  [9.99958038e-01 1.39727435e-05 8.53342463e-09 ... 3.93045041e-10
   8.69602809e-06 1.72742872e-07]
  [9.99927640e-01 2.61714085e-05 1.06789457e-08 ... 5.08691533e-10
   1.43297557e-05 2.41697620e-07]]

 [[3.27781436e-06 8.73282770e-05 3.98219745e-05 ... 2.15375656e-03
   1.71466311e-07 7.27040879e-06]
  [3.22034089e-06 3.25348879e-06 3.01405088e-08 ... 5.20505535e-04
   4.57724326e-07 5.09031906e-06]
  [1.76283920e-05 2.67665531e-03 1.95851699e-05 ... 8.73912999e-04
   4.45054809e-07 3.72678073e-07]
  ...
  [9.99973893e-01 7.66020548e-06 7.66533859e-09 ... 3.24128946e-10
   4.99837

In [ ]:
def logits_to_tokens(sequences, index):
    token_sequences = []
    for categorical_sequence in sequences:
        token_sequence = []
        for categorical in categorical_sequence:
            token_sequence.append(index[np.argmax(categorical)])
 
        token_sequences.append(token_sequence)
 
    return token_sequences

In [ ]:
print(logits_to_tokens(predictions, {i: t for t, i in tag2index.items()}))

[['VBG', 'VBZ', 'RB', 'JJ', 'IN', 'PRP', '.', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', '-PAD-', 